name: auto-deploy with docker

on:
  push:
    branches:
      - main

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
      - name: git repository 소스 복사
        uses: actions/checkout@v4

      - name: jdk 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

#      - name: application.properties 복사

      - name: build jar
        run: chmod +x ./gradlew && ./gradlew clean build

      - name: docker image 빌드
        run: docker build -t ${{secrets.DOCKER_USER}}/web-app:latest .

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: docker image pull
        run: docker push ${{secrets.DOCKER_USER}}/web-app:latest

  deploy-job:
    needs: build-job
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        run: echo "hello world"
